// <auto-generated />
using BackendInterviewTask.Infra.Persistence.EfCoreSQlite.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendInterviewTask.Infra.Persistence.EfCoreSqlite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240509232317_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("BackendInterviewTask.Domain.Domain.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "https://api.dicebear.com/8.x/pixel-art/png?seed=john&size=150"
                        },
                        new
                        {
                            Id = 2,
                            Url = "https://api.dicebear.com/8.x/pixel-art/png?seed=jane&size=150"
                        },
                        new
                        {
                            Id = 3,
                            Url = "https://api.dicebear.com/8.x/pixel-art/png?seed=aneka&size=150"
                        },
                        new
                        {
                            Id = 4,
                            Url = "https://api.dicebear.com/8.x/pixel-art/png?seed=flix&size=150"
                        },
                        new
                        {
                            Id = 5,
                            Url = "https://api.dicebear.com/8.x/pixel-art/png?seed=default&size=150"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
